config/routes.rb
Rails.application.routes.draw do

  class Auth # used to authenticate requests to /delayed_job
    def matches?(request)
      return false unless request.session.to_hash['enable_admin_pages']
      return request.session.to_hash['enable_admin_pages']
    end
  end

  get '/healthcheck', to: 'application#healthcheck'

  # OmniAuth login mappings
  get '/auth/:provider/callback', to: 'sessions#create', as: :signin
  get '/signout',  to: 'sessions#destroy', as: :signout
  get '/not_authorized', to: "sessions#not_authorized", as: :not_authorized

  get '/email', to: 'application#email' # TODO replaceappname - For test purposes - remove after email test is successful

  get '/main', to: 'things#index'
  get '/new', to: 'things#new'
  get '/show', to: 'things#show'
  get '/edit', to: 'things#edit'
  post '/create', to: 'things#create'
  get '/delete', to: 'things#delete'
  post '/update', to: 'things#update'

  unless %{production test}.include?(Rails.env)
    mount LetterOpenerWeb::Engine, at: "/test_emails"
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post], as: 'dj', constraints: Auth.new

  # TODO replaceappname - For test purposes - remove/update before using
  resources :users, only: [:index]

  root 'things#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thing.rb
class Thing < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  include DartServiceUser::Rails

  validates_uniqueness_of :netid, :case_sensitive => false
  validates_presence_of :netid
  validates_presence_of :name

  default_scope { order('lastname, firstname') }

  def is_admin
    'admin' == role
  end

end

app/models/worker.rb
require 'pty'
class Worker

  def self.start
    
    worker_file_path = "#{Dir.tmpdir}/worker_pid"
    File.delete(worker_file_path) if File.exist?(worker_file_path)
    
    exception = nil
    begin
      PTY.spawn( "RAILS_ENV=#{Rails.env} QUEUES=mailers rake jobs:work" ) do |stdout, stdin, pid|
        begin
          File.open(worker_file_path, 'w') {|f| f.write(pid) }
          puts "spawned rake job pid: #{pid}\n"
          stdout.each { |line| print line }
        rescue Errno::EIO
          puts "=======> CATCHING KILLING THE RAKE TASK HERE <=========="
          exception = Errno::EIO
        end
      end
    rescue PTY::ChildExited
      puts "The child process exited!"
      exception = PTY::ChildExited
    rescue => e
      puts "delayed_job worker failed: #{e}"
      exception = e
    end
    puts "returning from worker.start"
    exception = RuntimeError.new("delayed job worker rake task was restarted") if exception.nil?
    ExceptionNotifier.notify_exception(exception)
    sleep 5 # allow time for puma to settle and quit if that's what killed our worker
    Thread.new { Worker.start }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # All actions in all controllers require logging in first
  before_action :authenticated?, except: [:healthcheck]

  helper_method :current_user, :logged_in?   # Helper methods are available in Views as well

  def healthcheck
    begin
      c = User.count
    rescue => ex
      render plain: "FAIL", status: :internal_server_error and return
    end
    render plain: "OK"
  end

  def email
    # TODO replaceappname - remove once email test is successful
    ExampleMailer.test_email(current_user.id).deliver_later
    redirect_to root_path and return
  end

  protected

  def logged_in?
    return false if session[:netid].blank?
    current_user.present?
  end

  def authenticated?
    unless logged_in?
      session[:return_url]=request.url
      redirect_to("/auth/cas")
      return false
    end
    true
  end

  private
  def current_user
    # If we already have a current_user, don't do anything
    # Otherwise, look it up from the session if the session id is set
    @current_user ||= User.find_by(netid: session[:netid]) if session[:netid]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticated? # Don't need to be logged in to see the login / logout pages

  def create
    session[:enable_admin_pages] = false
    user = User.find_by(netid: auth_hash['extra']['netid'])
    if user
      session[:netid] = user.netid
      flash[:success] = "Signed in as #{user.name}"

      # Check auth for admin paths - in this case they have a user record, so set true
      # In other apps further permissions can be checked e.g. admin user type
      session[:enable_admin_pages] = true

      redirect_to session[:return_url] || root_path
    else
      redirect_to not_authorized_path
    end
  end

  def destroy
    app = "replaceappname"
    url = case Rails.env
    when 'dev' then "https://#{app}-dev.dartmouth.edu/"
    when 'preprod' then  "https://#{app}-preprod.dartmouth.edu/"
    when 'production' then "https://#{app}.dartmouth.edu/"
          else
            root_url
          end
    reset_session # Dump all stored session hashes incl. netid
    redirect_to "https://login.dartmouth.edu/logout.php?app=#{app}&url=#{url}"
  end

  def not_authorized
    render plain: "You do not have access to this functionality"
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController

    def index
    end

    def new
    end

    def edit
    end

    def create
        flash[:success] = "A new Thing has been successfully created (but not really)."
        redirect_to root_path
    end

    def delete
        flash[:success] = "The Thing has been successfully deleted (but not really)."
        redirect_to root_path
    end

    def update
        flash[:success] = "The Thing has been successfully updated (but not really)."
        redirect_to show_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def app_version
    "0.3.1"
  end

  def app_title
    "replaceappname"
  end

end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def nav_tabs
    return "" unless logged_in? && current_user
    main_tab_active = false
    thing_tab_active = false

    case controller.controller_name
    when 'application'
        main_tab_active = true
    when 'things'
        if controller.action_name == 'new'
          main_tab_active = true
        else
          thing_tab_active = true
        end
    end

    tabs = Array.new
    tabs << content_tag(:li, link_to("Home", root_path, class: 'nav-link'), :class => (main_tab_active == true ? 'nav-item active' : 'nav-item'))
    tabs << content_tag(:li, link_to("Thing X", show_path, class: 'nav-link'), :class => (thing_tab_active == true ? 'nav-item active' : 'nav-item'))
    tabs << content_tag(:li, link_to("Thing Y", root_path, class: 'nav-link'), class: 'nav-item')
    tabs.join('').html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-us">
<head>
  <title><%= content_for?(:title) ? "#{app_title} - #{yield(:title)}" : app_title %></title>
  <script src="//code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="//code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
  <script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

  <script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.14.0/jquery.validate.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
  <script src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>

  <script src="//cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>

  <link href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" rel="stylesheet" />
  <link rel="stylesheet" href="//cdn.dartmouth.edu/assets/bootstrap/4.1.0/bootstrap.css">
  <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

  <link href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" rel="stylesheet" />
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>

  <%= yield :head_css %>
  <%= csrf_meta_tags %>
  <%= yield :head_script %>
  <script>
    //Single-click only on submit
    $(document).ready(function() {
      $("button[type=submit],input[type=submit] :not([data-disable-with])").each(function(index, element) {
        $(this).attr('data-disable-with', 'Submitting...');
      });
      $('.prevent_dbl_click').click(function(e) {
        if (!$(this).data('disabled')) {
          $(this).attr('data-disabled', 'true');
        }
        else {
          e.preventDefault();
        }
      });
    });

    //Override the default confirm dialog by rails
    $.rails.allowAction = function(link){
      if (link.data("confirm") == undefined){
        return true;
      }
      $.rails.showConfirmationDialog(link);
      return false;
    }

    //User click confirm button
    $.rails.confirmed = function(link){
      link.data("confirm", null);
      link.trigger("click.rails");
    }

    //Display the confirmation dialog
    $.rails.showConfirmationDialog = function(link){
      var message = link.data("confirm");
      swal({
        title: "Warning",
        type:'warning',
        html: message,
        confirmButtonText: "Yes",
        confirmButtonClass: "btn btn-danger swal_button",
        cancelButtonClass: "btn btn-default swal_button",
        buttonsStyling: false,
        reverseButtons: true,
        showCancelButton: true,
        focusCancel: true
      }).then(function(e){
        $.rails.confirmed(link);
      });
    };

  </script>

</head>
<body>
  <header id='page-header'>
    <div id='user-details'>
      <% if current_user %>
        <span class='hide-small'><i class="fa fa-user"></i><span class='hide-medium'>Signed in as </span><%= current_user.name %>
        <a href="/signout"><span class='hide-medium'>Sign out </span></a></span><a href="/signout"><i class="fa fa-sign-out-alt"></i></a>
      <% else %>
        <%= link_to "Sign in", "/auth/cas" %>
      <% end %>
    </div>
    <div id='topbar'>
    </div>
    <div id='headerbar'>
      <div class='container'>
        <nav id='main-nav' class='navbar navbar-dark  navbar-expand-md' role='navigation'>
          <a class="navbar-brand" href="/" title='Home'>
            <img class='logo' src="assets/logo.png" class="d-inline-block align-top" alt="Logo">
            <span class='app-name'><%= app_title %></span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header-tabs-collapse" aria-controls="header-tabs-collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="header-tabs-collapse">
            <ul class="nav nav-tabs" id='header-tabs'>
              <%= nav_tabs %>
            </ul>
          </div>
        </nav>
      </div>
    </div>
  </header>

  <div id='page-area'>
    <div id='masthead'>
      <div class='container'>
        <h1 class='full_width_masthead'><%= content_for?(:title) ? yield(:title) : 'replaceappname' %></h1>
        <div class='float-right'>
          <%= (Rails.env.production? ? "" : link_to("See Emails Produced (TEST ONLY)", "/test_emails", target: "_blank", class: "test_emails")) %>
        </div>
      </div>
    </div>
    <div id='content' class='container'>
      <div class='flash' id='flash-message'>
        <% flash.each do |type, message| %>
          <div class='alert alert-<%= type %>'>
            <%= message.html_safe if message.is_a? String %>
            <button class='close' data-dismiss='alert' type='button'>×</button>
          </div>
        <% end %>
      </div>
      <% if content_for?(:page_actions) %>
        <nav id='page-nav' class='navbar'>
          <ul class='nav'>
            <%= yield(:page_actions) %>
          </ul>
        </nav>
      <% end %>
      <%= yield %>
    </div>
  </div>

  <footer id='page-footer'>
    <div class='container'>
      &copy; <%= Date.today.year %> <a href='http://www.dartmouth.edu'>Dartmouth College</a> <span class='version'>v<%= app_version %></span>
    </div>
  </footer>
</body>

<script>
$("input:not([type=checkbox]):not([type=hidden]):not([type=radio]):not([type=button]):not([type=submit])").each(function(index,element)
  { $(this).addClass('form-control') })
$("select").each(function(index,element) { $(this).addClass('form-control') })
$("textarea").each(function(index,element) { $(this).addClass('form-control') })
</script>

</html>

app/views/things/edit.html.erb
<% title "Edit Thing X" %>

<div id="edit-thing class="row"">
    <div class="col-sm-11"> 

        <%= form_for(:thing, :url => update_path, :html => { :class=>"form-horizontal" }) do |f| %>

            <%= f.hidden_field :user_id, :value => current_user.id %>
        
            <div class="form-group">
                <%= f.label :title, "Thing Name *", class: "col-sm-3 control-label" %>
                <div class="col-sm-9">
                    <%= f.text_field :title, :size => 80, :value => "Thing X", :disabled => true %>
                </div>
            </div>

            <div class="form-group">
                <%= f.label :thing_type, "Thing Type *", class: "col-sm-3 control-label" %>
                <div class="col-sm-9">
                    <%= select_tag :thing_type, options_for_select([['Animal', 1], ['Vegetable', 2], ['Mineral', 3]], 3), {:include_blank => true} %>
                </div>
            </div>

            <div class="form-group">
                <%= f.label :contact_information, "Contact Information", class: "col-sm-3 control-label" %>
                <div class="col-sm-9">
                    <%= f.text_area :contact_information, :size => '80x4', :value => "Some Person\r\n4 Currier Drive (I91 exit 13, right on West St, straight at traffic light, left on Currier, first right into parking lot, arrive before 5am to find an empty parking space)\r\nHanover, NH  03755\r\n603.646.2660\r\nsome.person@dartmouth.edu" %>
                    <p class="help-block">Note: If you leave this blank, users will be instructed to contact you via your dartmouth.edu email account.</p>
                </div>
            </div>

            <div class="form-group">
                <%= f.label :season, "Season(s)", class: "col-sm-3 control-label" %>
                <div class="col-sm-9">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="final[season][]" value="Fall" id="season_0" checked  /> Fall
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="final[season][]" value="Winter" id="season_1" checked /> Winter
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="final[season][]" value="Spring" id="season_2" /> Spring
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="final[season][]" value="Summer" id="season_3" /> Summer
                        </label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <%= f.label :time_commitment, "Time Commitment", class: "col-sm-3 control-label" %>
                <div class="col-sm-9">
                    <div class="radio">
                        <label>
                            <input type="radio" name="final[time_commitment][]" value="Full-time" id="final_time_commitment_0" checked /> Full-time
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="final[time_commitment][]" value="Part-time" id="final_time_commitment_1" /> Part-time
                        </label>
                    </div>
                </div>
            </div>

            <div class="form-group button_row">
                <div class="col-sm-offset-3 col-sm-9">
                    <button class="button btn btn-primary" type="submit" data-disable-with="Submitting...">
                        Save
                    </button>
                    <a class="btn btn-default" href="<%= show_path %>">Cancel</a>
                </div>
            </div>

        <% end %>
    </div>

    <div class="col-sm-1"></div>
</div>


app/views/things/index.html.slim
- title "replaceappname main page"
- content_for :head_script do
  javascript:
    function emailFunction() {
      swal({
          title: "Warning",
          type:'warning',
          html: 'You are about to send an email to yourself.<br/><br/><b>Are you sure?</b> ',
          confirmButtonText: "Yes",
          confirmButtonClass: "btn btn-danger swal_button",
          cancelButtonClass: "btn btn-default swal_button",
          buttonsStyling: false,
          showCancelButton: true,
          reverseButtons: true,
          focusCancel: true
        }).then(function(){
            window.location.href = "#{email_path}";
        }, function(dismiss){
          swal({
            title:"Canceled",
            type:'info',
            text: "Close call, email was not sent.",
            confirmButtonText: "Phew!",
            confirmButtonClass: "btn btn-primary swal_button",
            buttonsStyling: false
          })
      })
    }

- content_for :page_actions do
  li
    div.action_link = link_to "Home", root_path
  /Extra page level actions go here
  li
    div.action_link = link_to "New", new_path
  li
    div.action_link = link_to "Send Email", "javascript:emailFunction()"

/Demo table for testing page length and scrolling
table.table.sortable
  thead
    tr
      th Thing
      th Description
      th Date
  tbody
    - 20.times do
      tr
        - n = (65 + rand(25)).chr
        td = link_to 'Thing ' + n, show_path
        td = 'Thing description ' + n
        - d = (Date.today + rand(60).days)
        td data-order=d.strftime('%Y-%m-%d') = d.strftime('%d %b %Y')

/Modal dialog for Action button

button.btn.btn-primary type="button" data-toggle="modal" data-target="#exampleModal" Launch demo modal

div.modal.fade id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"
  div.modal-dialog role="document"
    form.form-horizontal url=root_path
      div.modal-content
        div.modal-header
          h3#exampleModalLabel.modal-title Modal title
          button.close type="button" data-dismiss="modal" aria-label="Close"
            span aria-hidden="true" &times;
        div.modal-body
          div.row
            div.col-sm-1
            div.col-sm-10
              div.form-group
                label.col-sm-3.control-label NetID
                div.col-sm-9
                  input
            div.col-sm-1
        div.modal-footer
          button.btn.btn-default type="button" data-dismiss="modal" Cancel
          button.btn.btn-primary type="submit" Save

app/views/things/new.html.erb
<% title "Add a New Thing" %>

<div id="new-thing class="row"">
    <div class="col-sm-11"> 

        <%= form_for(:thing, :url => create_path, :html => { :class=>"form-horizontal" }) do |f| %>

            <%= f.hidden_field :user_id, :value => current_user.id %>
        
            <div class="form-group">
                <%= f.label :title, "Thing Name *", class: "col-sm-3 control-label" %>
                <div class="col-sm-9">
                    <%= f.text_field :title, :size => 80 %>
                </div>
            </div>

            <div class="form-group">
                <%= f.label :thing_type, "Thing Type *", class: "col-sm-3 control-label" %>
                <div class="col-sm-9">
                    <%= select_tag :thing_type, options_for_select([['Animal', 1], ['Vegetable', 2], ['Mineral', 3]]), {:include_blank => true} %>
                </div>
            </div>

            <div class="form-group">
                <%= f.label :contact_information, "Contact Information", class: "col-sm-3 control-label" %>
                <div class="col-sm-9">
                    <%= f.text_area :contact_information, :size => '80x4' %>
                    <p class="help-block">Note: If you leave this blank, users will be instructed to contact you via your dartmouth.edu email account.</p>
                </div>
            </div>

            <div class="form-group">
                <%= f.label :season, "Season(s)", class: "col-sm-3 control-label" %>
                <div class="col-sm-9">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="final[season][]" value="Fall" id="season_0"  /> Fall
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="final[season][]" value="Winter" id="season_1" /> Winter
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="final[season][]" value="Spring" id="season_2" /> Spring
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="final[season][]" value="Summer" id="season_3" /> Summer
                        </label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <%= f.label :time_commitment, "Time Commitment", class: "col-sm-3 control-label" %>
                <div class="col-sm-9">
                    <div class="radio">
                        <label>
                            <input type="radio" name="final[time_commitment][]" value="Full-time" id="final_time_commitment_0"  /> Full-time
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="final[time_commitment][]" value="Part-time" id="final_time_commitment_1" /> Part-time
                        </label>
                    </div>
                </div>
            </div>

            <div class="form-group button_row">
                <div class="col-sm-offset-3 col-sm-9">
                    <button class="button btn btn-primary" type="submit" data-disable-with="Submitting...">
                        Create
                    </button>
                    <a class="btn btn-default" href="<%= root_path %>">Cancel</a>
                </div>
            </div>

        <% end %>
    </div>

    <div class="col-sm-1"></div>
</div>


app/views/things/show.html.erb
<% title "Thing X" %>

<% content_for :page_actions do %>
    <li><%= link_to content_tag(:span, "Edit"), edit_path %></li>
    <li><%= link_to content_tag(:span, "Delete"), delete_path, method: :get, :data => {:confirm => 'Are you sure you want to <strong>permanently</strong> delete this thing?'} %></li>
<% end %>

<div class="row" id="thing-information" >
    <div class="col-sm-1"></div>
    <div class="col-sm-10"> 

        <div class="row">
            <label class="col-sm-3 item_label">
                Thing Name:
            </label>
            <div class="col-sm-9 item_value">
                Thing X
            </div>
        </div>

        <div class="row">
            <label class="col-sm-3 item_label">
                Thing Type:
            </label>
            <div class="col-sm-9 item_value">
                Mineral
            </div>
        </div>
    
        <div class="row">
            <label class="col-sm-3 item_label">
                Contact Information:
            </label>
            <div class="col-sm-9 item_value">
                Some Person<br/>
                4 Currier Drive (I91 exit 13, right on West St, straight at traffic light, left on Currier, first right into parking lot, arrive before 5am to find an empty parking space)<br/>
                Hanover, NH  03755<br/>
                603.646.2660<br/>
                some.person@dartmouth.edu
            </div>
        </div>

        <div class="row">
            <label class="col-sm-3 item_label">
                Season(s):
            </label>
            <div class="col-sm-9 item_value">
                Fall, Winter
            </div>
        </div>

        <div class="row">
            <label class="col-sm-3 item_label">
                Time Commitment:
            </label>
            <div class="col-sm-9 item_value">
                Full-time
            </div>
        </div>

        <div class="row button_row">
            <div class="col-sm-offset-3 col-sm-9">
                <%= link_to 'Cancel', root_path, :class => "btn btn-default" %>
            </div>
        </div>
    </div>
        
    <div class="col-sm-1"></div>
</div> 